language: ruby
sudo: false

cache: bundler

bundler_args: --no-deployment --binstubs=./bin

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
  - gem update bundler

install:
  - bundle install --path vendor/bundle

script:
   - echo $BUNDLE_GEMFILE
   - bundle exec rake
gemfile:
  - gemfiles/rails_4.0.0.gemfile
  - gemfiles/rails_4.1.1.gemfile
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_5.0.0.gemfile
  - gemfiles/rails_5.0.2.gemfile
  - gemfiles/rails_5.1.0.rc1.gemfile
matrix:
  exclude:
  - rvm: 2.4.0
    gemfile: gemfiles/rails_4.0.0.gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/rails_4.1.1.gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/rails_4.2.0.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_4.0.0.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_4.1.1.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_4.2.0.gemfile
rvm:
  - 2.2.2
  - 2.2.5
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.4.0
  - 2.4.1
notifications:
  email: false
